consul:
  extends:
    file: docker-compose.yml
    service: consul
  ports:
    - 8500:8500
cloudapi:
  extends:
    file: docker-compose.yml
    service: cloudapi
  links:
    - consul:consul
  environment:
    - PORT=3000
    - ROOT_URL=http://localhost:3000
    - CONSUL=consul
