fast-node:
  build: .
  environment:
    - TYPE=node
  ports:
   - "8000"
fast-artillery:
  build: .
  environment:
    - TYPE=artillery
    - MODE=fast
  links:
    - fast-node:fast-node
slow-node:
  build: .
  environment:
    - TYPE=node
  ports:
   - "8000"
slow-artillery:
  build: .
  environment:
    - TYPE=artillery
    - MODE=slow
  links:
    - slow-node:slow-node
plain-node:
  build: .
  environment:
    - TYPE=node
  ports:
   - "8000"
plain-artillery:
  build: .
  environment:
    - TYPE=artillery
    - MODE=plain
  links:
    - plain-node:plain-node
telemetry:
  build: ./prometheus
  ports:
   - "9090"
  environment:
    - TYPE=telemetry
  links:
    - fast-node:fast-node
    - slow-node:slow-node
    - plain-node:plain-node
