no-leak-node-1:
  build: .
  environment:
    - TYPE=node
  ports:
   - "8000"
no-leak-artillery-1:
  build: .
  environment:
    - TYPE=artillery
    - MODE=no-leak-1
  links:
    - no-leak-node-1:no-leak-node-1
no-leak-node-2:
  build: .
  environment:
    - TYPE=node
  ports:
   - "8000"
no-leak-artillery-2:
  build: .
  environment:
    - TYPE=artillery
    - MODE=no-leak-2
  links:
    - no-leak-node-2:no-leak-node-2
no-leak-node-3:
  build: .
  environment:
    - TYPE=node
  ports:
   - "8000"
no-leak-artillery-3:
  build: .
  environment:
    - TYPE=artillery
    - MODE=no-leak-3
  links:
    - no-leak-node-3:no-leak-node-3
telemetry:
  build: ./prometheus
  ports:
   - "9090"
  environment:
    - TYPE=telemetry
  links:
    - no-leak-node-3:no-leak-node-3
    - no-leak-node-2:no-leak-node-2
    - no-leak-node-1:no-leak-node-1
