consul:
  image: autopilotpattern/consul:0.7.2-r0.8
  command: >
    /usr/local/bin/containerpilot
    /bin/consul agent -server
      -config-dir=/etc/consul
      -log-level=err
      -bootstrap-expect 1
      -ui-dir /ui
  restart: always
  mem_limit: 128m
  ports:
    - 8500:8500
  dns:
    - 127.0.0.1
compose-api:
  image: joyent/copilot-compose
  links:
    - consul:consul
  expose:
    - 4242
  env_file:
    - ../../_env
  environment:
    - CONSUL=consul
  restart: always
rethinkdb:
  image: autopilotpattern/rethinkdb:2.3.5r1
  restart: always
  mem_limit: 1g
  links:
    - consul:consul
  environment:
    - CONSUL=consul
    - CONSUL_AGENT=1
  ports:
    - 8080:8080
    - 28015:28015
    - 29015:29015
  dns:
    - 127.0.0.1
api:
  build: ./
  dockerfile: ./test-Dockerfile
  links:
    - consul:consul
    - rethinkdb:rethinkdb
    - compose-api:compose-api
  env_file:
    - ../../_env
  environment:
    - CONSUL=consul
  expose:
    - 9090
  dns:
    - 127.0.0.1
